version: '3'

vars:
  BINARY_NAME: bt
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  LDFLAGS: -ldflags "-s -w -X main.version={{.VERSION}}"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - go build -buildvcs=false {{.LDFLAGS}} -o {{.BINARY_NAME}} ./cmd/bt
    sources:
      - '**/*.go'
      - go.mod
      - go.sum
    generates:
      - '{{.BINARY_NAME}}'

  build:all:
    desc: Build binaries for all platforms
    cmds:
      - task: build:linux
      - task: build:darwin
      - task: build:windows

  build:linux:
    desc: Build for Linux (amd64, arm64)
    cmds:
      - GOOS=linux GOARCH=amd64 go build {{.LDFLAGS}} -o dist/{{.BINARY_NAME}}-linux-amd64 ./cmd/bt
      - GOOS=linux GOARCH=arm64 go build {{.LDFLAGS}} -o dist/{{.BINARY_NAME}}-linux-arm64 ./cmd/bt

  build:darwin:
    desc: Build for macOS (amd64, arm64)
    cmds:
      - GOOS=darwin GOARCH=amd64 go build {{.LDFLAGS}} -o dist/{{.BINARY_NAME}}-darwin-amd64 ./cmd/bt
      - GOOS=darwin GOARCH=arm64 go build {{.LDFLAGS}} -o dist/{{.BINARY_NAME}}-darwin-arm64 ./cmd/bt

  build:windows:
    desc: Build for Windows (amd64)
    cmds:
      - GOOS=windows GOARCH=amd64 go build {{.LDFLAGS}} -o dist/{{.BINARY_NAME}}-windows-amd64.exe ./cmd/bt

  install:
    desc: Install the binary to GOPATH/bin
    cmds:
      - go install {{.LDFLAGS}} ./cmd/bt

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -rf dist/

  fmt:
    desc: Format Go source code
    cmds:
      - go fmt ./...

  lint:
    desc: Run linter (requires golangci-lint)
    cmds:
      - golangci-lint run ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  test:
    desc: Run all tests with verbose output
    cmds:
      - go test -v ./...

  test:short:
    desc: Run tests without verbose output
    cmds:
      - go test ./...

  test:race:
    desc: Run tests with race detector
    cmds:
      - go test -race -v ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
    generates:
      - coverage.out
      - coverage.html

  test:unit:
    desc: Run unit tests only (excludes e2e)
    cmds:
      - go test -v ./internal/...

  test:e2e:
    desc: Run e2e tests (requires network access)
    cmds:
      - go test -v ./e2e/...
    env:
      E2E_TEST: "1"

  test:e2e:short:
    desc: Run e2e tests without verbose output
    cmds:
      - go test ./e2e/...
    env:
      E2E_TEST: "1"

  test:all:
    desc: Run all tests (unit + e2e)
    cmds:
      - task: test:unit
      - task: test:e2e

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  check:
    desc: Run all checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test

  dev:
    desc: Build and run with arguments
    cmds:
      - go run ./cmd/bt {{.CLI_ARGS}}

  watch:
    desc: Watch for changes and rebuild (requires watchexec)
    cmds:
      - watchexec -e go -r -- task build

  release:dry:
    desc: Dry run of goreleaser
    cmds:
      - goreleaser release --snapshot --clean

  deps:
    desc: Download dependencies
    cmds:
      - go mod download

  deps:update:
    desc: Update all dependencies
    cmds:
      - go get -u ./...
      - go mod tidy
